package org.omg.DynamicAny;


/**
* org/omg/DynamicAny/DynStruct.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /build/openjdk-lts-Ae5PRQ/openjdk-lts-10.0.2+13/src/java.corba/share/classes/org/omg/DynamicAny/DynamicAny.idl
* Friday, November 16, 2018 at 3:15:33 PM Coordinated Universal Time
*/


/**
    * DynStruct objects support the manipulation of IDL struct and exception values.
    * Members of the exceptions are handled in the same way as members of a struct.
    */
public interface DynStruct extends DynStructOperations, org.omg.DynamicAny.DynAny, org.omg.CORBA.portable.IDLEntity 
{
} // interface DynStruct
