#!/bin/bash

CE()
{
	echo -ne "\e[$1"
}

CC()
{
	echo -ne "\e[$1m"
}

ENDCC()
{
	CC '0'
}

BLACK()
{
	CC '0;30'
}

L_BLACK()
{
	CC '1;30'
}

RED()
{
	CC '0;31'
}

L_RED()
{
	CC '1;31'
}

GREEN()
{
	CC '0;32'
}

L_GREEN()
{
	CC '1;32'
}

BROWN()
{
	CC '0;33'
}

YELLOW()
{
	CC '1;33'
}

BLUE()
{
	CC '0;34'
}

L_BULE()
{
	CC '1;34'
}

PURPLE()
{
	CC '0;35'
}

L_PURPLE()
{
	CC '1;35'
}

CYAN()
{
	CC '0;36'
}

L_CYAN()
{
	CC '1;36'
}

GRAY()
{
	CC '0;37'
}

WHITE()
{
	CC '1;37'
}

# BG_* 背景

BG_BLACK()
{
	CC '40'
}

BG_RED()
{
	CC '41'
}

BG_GREEN()
{
	CC '42'
}

BG_YELLOW()
{
	CC '43'
}

BG_BLUE()
{
	CC '44'
}

BG_PURPLE()
{
	CC '45'
}

BG_CYAN()
{
	CC '46'
}

BG_WHITE()
{
	CC '47'
}

#粗体
BOLD()
{
	CC '1'
}

#下划线
UNDERLINE()
{
	CC '4'
}

#一闪一闪亮晶晶
BLINK()
{
	CC '5'
}

#反色
REVERSE()
{
	CC '7'
}

#隐藏输出
HIDE()
{
	CC '8'
}

#clear
CLEAR()
{
	CE '2J'
}

#删除至行末
CLRLINE()
{
	CE 'K'
}

#删除行
DELLINE()
{
	echo -ne "\r"
	CLRLINE
}

cursor_up()
{
	CE $1A
}

cursor_down()
{
	CE $1B
}

cursor_right()
{
	CE $1C
}

cursor_left()
{
	CE $1D
}

#移动光标至 坐标($1,$2)处
set_cursor()
{
	CE "$2;$1H"
}

#记录光标坐标
mark_cursor()
{
	CE s
}

#恢复上次光标坐标
unmark_cursor()
{
	CE u
}

#隐藏光标
hide_cursor()
{
	CE ?25l
}

#不隐藏光标
unhide_cursor()
{
	CE ?25h
}

