package org.omg.Messaging;


/**
* org/omg/Messaging/SYNC_WITH_TRANSPORT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /build/openjdk-lts-Ae5PRQ/openjdk-lts-10.0.2+13/src/java.corba/share/classes/org/omg/PortableInterceptor/Messaging.idl
* Friday, November 16, 2018 at 3:15:36 PM Coordinated Universal Time
*/

public interface SYNC_WITH_TRANSPORT
{

  /**
     * Constant, defined in the Messaging spec, to define how far the 
     * request shall progress before control is returned to the client.
     */
  public static final short value = (short)(1);
}
