#!/bin/bash

#----DIY

export JNI_PATH=/usr/lib/jvm/java-11-openjdk-amd64/include
export JVM_PATH=/usr/lib/jvm/java-11-openjdk-amd64/lib/server

alias ccj=.sh
# g++ -I $JNI_PATH -I $JNI_PATH/linux ${1}.cpp -o $1 -L $JVM_PATH -ljvm

#----DIY

<<!

echo $JVM_PATH >> /etc/ld.so.conf
/sbin/ldconfig -v

javap -s -p xx1.class
ccj 001

!
