#!/bin/bash

#----DIY

export CLASSPATH=/home/k24/java/CLASS
export JNI_PATH=/usr/lib/jvm/java-11-openjdk-amd64/include

alias jc='javac -d $CLASSPATH'
alias jh='javah -classpath $CLASSPATH/..'
alias jcc='g++ -I $JNI_PATH -I $JNI_PATH/linux'

#----DIY

