package org.omg.PortableServer;


/**
* org/omg/PortableServer/IMPLICIT_ACTIVATION_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /build/openjdk-lts-Ae5PRQ/openjdk-lts-10.0.2+13/src/java.corba/share/classes/org/omg/PortableServer/poa.idl
* Friday, November 16, 2018 at 3:15:37 PM Coordinated Universal Time
*/

public interface IMPLICIT_ACTIVATION_POLICY_ID
{

  /**
  	 * The value representing IMPLICIT_ACTIVATION_POLICY_ID.
  	 */
  public static final int value = (int)(20L);
}
