package org.omg.PortableServer;


/**
* org/omg/PortableServer/ServantRetentionPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /build/openjdk-lts-Ae5PRQ/openjdk-lts-10.0.2+13/src/java.corba/share/classes/org/omg/PortableServer/poa.idl
* Friday, November 16, 2018 at 3:15:37 PM Coordinated Universal Time
*/


/**
	 * This policy specifies whether the created POA retains 
	 * active servants in an Active Object Map. 
	 */
public interface ServantRetentionPolicy extends ServantRetentionPolicyOperations, org.omg.CORBA.Policy, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServantRetentionPolicy
