package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/IORInterceptor_3_0.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /build/openjdk-lts-Ae5PRQ/openjdk-lts-10.0.2+13/src/java.corba/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Friday, November 16, 2018 at 3:15:35 PM Coordinated Universal Time
*/

public interface IORInterceptor_3_0 extends IORInterceptor_3_0Operations, org.omg.PortableInterceptor.IORInterceptor, org.omg.CORBA.portable.IDLEntity 
{
} // interface IORInterceptor_3_0
