package com.sun.corba.se.PortableActivationIDL;


/**
* com/sun/corba/se/PortableActivationIDL/ServerProxy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /build/openjdk-lts-Ae5PRQ/openjdk-lts-10.0.2+13/src/java.corba/share/classes/com/sun/corba/se/PortableActivationIDL/activation.idl
* Friday, November 16, 2018 at 3:15:29 PM Coordinated Universal Time
*/


/** Server callback interface, passed to Activator in registerServer method.
    */
public interface ServerProxy extends ServerProxyOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerProxy
