package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/Interceptor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /build/openjdk-lts-Ae5PRQ/openjdk-lts-10.0.2+13/src/java.corba/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Friday, November 16, 2018 at 3:15:35 PM Coordinated Universal Time
*/


/**
   * All Portable Interceptors implement Interceptor.
   */
public interface Interceptor extends InterceptorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Interceptor
